export const buildings = [
  {
    id: 'BLD_MEMBRANE_STORE',
    entityType: 'building',
    labelKey: 'building.membrane_store',
    requiresNodes: ['M01'],
    baseCost: { rna: 8 },
    growth: 1.25,
    maxCount: null,
    effects: [{ type: 'resource_capacity', resourceId: 'rna', value: 250 }],
  },
  {
    id: 'BLD_GENETIC_STORE',
    entityType: 'building',
    labelKey: 'building.genetic_store',
    requiresNodes: ['M03'],
    baseCost: { rna: 30, dna: 12 },
    growth: 1.25,
    maxCount: null,
    effects: [
      { type: 'resource_capacity', resourceId: 'dna', value: 150 },
    ],
  },
  {
    id: 'BLD_BIOMASS_STORE',
    entityType: 'building',
    labelKey: 'building.biomass_store',
    requiresNodes: ['M06'],
    baseCost: { dna: 25 },
    growth: 1.25,
    maxCount: null,
    effects: [{ type: 'resource_capacity', resourceId: 'biomass', value: 160 }],
  },
  {
    id: 'BLD_ATP_STORE',
    entityType: 'building',
    labelKey: 'building.atp_store',
    requiresNodes: ['C01'],
    baseCost: { biomass: 15 },
    growth: 1.25,
    maxCount: null,
    effects: [{ type: 'resource_capacity', resourceId: 'atp', value: 120 }],
  },
  {
    id: 'BLD_FOOD_STORE',
    entityType: 'building',
    labelKey: 'building.food_store',
    // T02 already exceeds the initial Food cap, so this must be available
    // immediately after a culture branch rather than after T05.
    requiresAnyBranchGroup: 'culture_1',
    baseCost: { food: 80, materials: 40 },
    growth: 1.25,
    maxCount: null,
    effects: [{ type: 'resource_capacity', resourceId: 'food', value: 500 }],
  },
  {
    id: 'BLD_MATERIALS_STORE',
    entityType: 'building',
    labelKey: 'building.materials_store',
    requiresAnyBranchGroup: 'culture_1',
    baseCost: { food: 50, materials: 45 },
    growth: 1.25,
    maxCount: null,
    effects: [{ type: 'resource_capacity', resourceId: 'materials', value: 400 }],
  },
  {
    id: 'BLD_KNOWLEDGE_ARCHIVE',
    entityType: 'building',
    labelKey: 'building.knowledge_archive',
    // T05 is the first discovery above the base Knowledge cap.
    requiresNodes: ['T02'],
    baseCost: { food: 100, materials: 60, knowledge: 25 },
    growth: 1.25,
    maxCount: null,
    effects: [{ type: 'resource_capacity', resourceId: 'knowledge', value: 300 }],
  },
  {
    id: 'BLD_POWER_STORE',
    entityType: 'building',
    labelKey: 'building.power_store',
    requiresNodes: ['T08'],
    baseCost: { materials: 360, knowledge: 160 },
    growth: 1.28,
    maxCount: null,
    effects: [{ type: 'resource_capacity', resourceId: 'power', value: 500 }],
  },
  {
    id: 'BLD_FIELD',
    entityType: 'building',
    labelKey: 'building.field',
    requiresNodes: ['T08'],
    requiresFlags: ['run.unlock.building.BLD_FIELD'],
    baseCost: { materials: 260, food: 180 },
    growth: 1.18,
    maxCount: null,
    effects: [
      { type: 'job_output_multiplier', jobId: 'JOB_SETTLEMENT_FARMER', value: 1.1, deferred: true, deferredUntil: 'jobs_system' },
    ],
  },
];
