export const goalStatuses = [
  'hidden',
  'revealed',
  'active',
  'completed',
  'reward_pending',
  'archived',
  'stalled',
  'blocked_by_event',
  'skipped_by_archive',
  'failed_soft',
];

export const goals = [
  {
    id: 'G001',
    title: 'Стабилизируйте энергетический градиент',
    description: 'Получите первые Energy через первичный процесс и завершите M01 Stable Bond.',
    targetTimeMs: 45000,
    nodeId: 'M01',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { nextGoalId: 'G002' },
    prerequisites: [],
    conditions: [{ type: 'node_completed', nodeId: 'M01' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M01', label: 'Развить Stable Bond' },
    highlight: { type: 'manual_process_or_node', targetId: 'MANUAL_PRIMORDIAL_PULSE' },
    hintTimeoutMs: 20000,
    hint: 'Используйте первичный процесс, затем купите Stable Bond за 12 Energy.',
  },
  {
    id: 'G002',
    title: 'Запустите саморепликацию',
    description: 'Накопите Energy и Information, затем завершите M02 Self Replication.',
    targetTimeMs: 120000,
    nodeId: 'M02',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G001', nextGoalId: 'G003' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M01' }],
    conditions: [{ type: 'node_completed', nodeId: 'M02' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M02', label: 'Развить Self Replication' },
    highlight: { type: 'producer', targetId: 'GEN_CATALYTIC_FOLD' },
    hintTimeoutMs: 45000,
    hint: 'Catalytic Fold производит Information; Energy Pocket ускоряет Energy после саморепликации.',
  },
  {
    id: 'G003',
    title: 'Создайте каталитическую РНК',
    description: 'Завершите M03 Catalytic RNA и откройте optional-узел Error Correction.',
    targetTimeMs: 240000,
    nodeId: 'M03',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G002', nextGoalId: 'G004' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M02' }],
    conditions: [{ type: 'node_completed', nodeId: 'M03' }],
    rewards: [{ type: 'reveal_entity', entityType: 'node', entityId: 'M04' }],
    cta: { type: 'node', targetId: 'M03', label: 'Развить Catalytic RNA' },
    highlight: { type: 'node', targetId: 'M03' },
    hintTimeoutMs: 60000,
    hint: 'Балансируйте Chemical Gradient, Catalytic Fold и Energy Pocket, чтобы не упереться в один ресурс.',
  },
  {
    id: 'G003_M04_OPTIONAL',
    title: 'Optional: исправьте ошибки копирования',
    description: 'M04 Error Correction усиливает Information, но не блокирует путь к Proto-cell.',
    targetTimeMs: 300000,
    nodeId: 'M04',
    chapterId: 'CH01',
    slot: 'side',
    optional: true,
    prerequisites: [{ type: 'node_completed', nodeId: 'M03' }],
    conditions: [{ type: 'node_completed', nodeId: 'M04' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M04', label: 'Развить Error Correction' },
    highlight: { type: 'node', targetId: 'M04' },
    hintTimeoutMs: 90000,
    hint: 'Это optional-ветка: можно взять бонус Information сейчас или двигаться к Lipid Shell.',
  },
  {
    id: 'G004',
    title: 'Создайте липидную оболочку',
    description: 'Завершите M05 Lipid Shell, чтобы усилить всё производство.',
    targetTimeMs: 420000,
    nodeId: 'M05',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G003', nextGoalId: 'G005' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M03' }],
    conditions: [{ type: 'node_completed', nodeId: 'M05' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M05', label: 'Развить Lipid Shell' },
    highlight: { type: 'node', targetId: 'M05' },
    hintTimeoutMs: 90000,
    hint: 'M04 полезен, но Lipid Shell остаётся основным путём к протоклетке.',
  },
  {
    id: 'G005',
    title: 'Создайте протоклетку',
    description: 'Завершите M06 Proto-cell, чтобы открыть Biomass и клеточную эру.',
    targetTimeMs: 600000,
    nodeId: 'M06',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G004' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M05' }],
    conditions: [{ type: 'node_completed', nodeId: 'M06' }],
    rewards: [{ type: 'set_flag', flag: 'milestone.proto_cell_reached', value: true }],
    cta: { type: 'node', targetId: 'M06', label: 'Развить Proto-cell' },
    highlight: { type: 'node', targetId: 'M06' },
    hintTimeoutMs: 120000,
    hint: 'Для Proto-cell нужны оба ресурса: держите производство Energy и Information примерно вместе.',
  },
  {
    id: 'G016',
    targetTimeMs: 3720000,
    nodeId: 'T08',
    chapterId: 'CH04',
    prerequisites: [{ type: 'node_completed', nodeId: 'T07' }],
    conditions: [{ type: 'node_completed', nodeId: 'T08' }],
  },
];
