export const goalStatuses = [
  'hidden',
  'revealed',
  'active',
  'completed',
  'reward_pending',
  'archived',
  'stalled',
  'blocked_by_event',
  'skipped_by_archive',
  'failed_soft',
];

export const goals = [
  {
    id: 'G001',
    title: 'Создайте устойчивую РНК',
    description: 'Запустите первичную реакцию, накопите RNA и завершите M01 Stable RNA.',
    targetTimeMs: 45000,
    nodeId: 'M01',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { nextGoalId: 'G002' },
    prerequisites: [],
    conditions: [{ type: 'node_completed', nodeId: 'M01' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M01', label: 'Развить Stable RNA' },
    highlight: { type: 'manual_process_or_node', targetId: 'MANUAL_PRIMORDIAL_PULSE' },
    hintTimeoutMs: 20000,
    hint: 'Используйте первичную реакцию, затем закрепите Stable RNA за 9 RNA.',
  },
  {
    id: 'G002',
    title: 'Запустите саморепликацию',
    description: 'Накопите RNA и завершите M02 Self Replication, чтобы реакция стала самоподдерживающейся.',
    targetTimeMs: 120000,
    nodeId: 'M02',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G001', nextGoalId: 'G003' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M01' }],
    conditions: [{ type: 'node_completed', nodeId: 'M02' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M02', label: 'Развить Self Replication' },
    highlight: { type: 'producer', targetId: 'PROC_RNA_REPLICATION' },
    hintTimeoutMs: 45000,
    hint: 'Primordial Reaction даёт раннюю RNA; после саморепликации станет доступен более сильный процесс копирования.',
  },
  {
    id: 'G003',
    title: 'Создайте ДНК',
    description: 'Завершите M03 DNA Synthesis, чтобы открыть DNA и optional-узел Error Correction.',
    targetTimeMs: 240000,
    nodeId: 'M03',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G002', nextGoalId: 'G004' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M02' }],
    conditions: [{ type: 'node_completed', nodeId: 'M03' }],
    rewards: [{ type: 'reveal_entity', entityType: 'node', entityId: 'M04' }],
    cta: { type: 'node', targetId: 'M03', label: 'Развить DNA Synthesis' },
    highlight: { type: 'node', targetId: 'M03' },
    hintTimeoutMs: 60000,
    hint: 'RNA остаётся основой роста; DNA появится после M03 и откроет следующий биологический слой.',
  },
  {
    id: 'G003_M04_OPTIONAL',
    title: 'Optional: исправьте ошибки копирования',
    description: 'M04 Error Correction усиливает DNA-процесс, но не блокирует путь к Membrane и Cell.',
    targetTimeMs: 300000,
    nodeId: 'M04',
    chapterId: 'CH01',
    slot: 'side',
    optional: true,
    prerequisites: [{ type: 'node_completed', nodeId: 'M03' }],
    conditions: [{ type: 'node_completed', nodeId: 'M04' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M04', label: 'Развить Error Correction' },
    highlight: { type: 'node', targetId: 'M04' },
    hintTimeoutMs: 90000,
    hint: 'Это optional-ветка: можно повысить точность копирования сейчас или двигаться к Membrane.',
  },
  {
    id: 'G004',
    title: 'Создайте мембрану',
    description: 'Завершите M05 Membrane, чтобы отделить внутреннюю среду будущей клетки.',
    targetTimeMs: 420000,
    nodeId: 'M05',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G003', nextGoalId: 'G005' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M03' }],
    conditions: [{ type: 'node_completed', nodeId: 'M05' }],
    rewards: [],
    cta: { type: 'node', targetId: 'M05', label: 'Развить Membrane' },
    highlight: { type: 'node', targetId: 'M05' },
    hintTimeoutMs: 90000,
    hint: 'M04 полезен, но Membrane остаётся основным путём к клетке.',
  },
  {
    id: 'G005',
    title: 'Создайте клетку',
    description: 'Завершите M06 Cell, чтобы открыть Biomass и клеточную эру.',
    targetTimeMs: 600000,
    nodeId: 'M06',
    chapterId: 'CH01',
    slot: 'chapter',
    sequence: { previousGoalId: 'G004', nextGoalId: 'G006' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M05' }],
    conditions: [{ type: 'node_completed', nodeId: 'M06' }],
    rewards: [{ type: 'set_flag', flag: 'milestone.cell_reached', value: true }],
    cta: { type: 'node', targetId: 'M06', label: 'Развить Cell' },
    highlight: { type: 'node', targetId: 'M06' },
    hintTimeoutMs: 120000,
    hint: 'Для Cell нужны RNA и DNA: синтезируйте DNA, но не обнуляйте RNA-основу роста.',
  },
  {
    id: 'G006',
    title: 'Стабилизируйте метаболизм',
    description:
      'Завершите C01 Metabolism, чтобы открыть ATP, и выберите один primary trait — Absorption, Symbiosis или Shell.',
    targetTimeMs: 780000,
    nodeId: 'C01',
    chapterId: 'CH02',
    slot: 'chapter',
    sequence: { previousGoalId: 'G005', nextGoalId: 'G007' },
    prerequisites: [{ type: 'node_completed', nodeId: 'M06' }],
    conditions: [
      { type: 'node_completed', nodeId: 'C01' },
      { type: 'branch_selected', branchGroup: 'cell_identity_1' },
    ],
    rewards: [],
    cta: { type: 'node', targetId: 'C01', label: 'Развить Metabolism' },
    highlight: { type: 'node', targetId: 'C01' },
    hintTimeoutMs: 90000,
    hint: 'Biomass уже накапливается после Cell; потратьте его на Metabolism, затем выберите один primary trait: Absorption ускоряет Biomass, Symbiosis даёт стабильный рост, Shell снижает потери. Выбор необратим для Timeline #1.',
  },
  {
    id: 'G007',
    title: 'Развейте клеточные системы',
    description: 'Завершите Protein Synthesis / Ribosome, Organelles и Cell Coordination (C03 -> C05 -> C06).',
    targetTimeMs: 1050000,
    nodeId: 'C06',
    chapterId: 'CH02',
    slot: 'chapter',
    sequence: { previousGoalId: 'G006' },
    prerequisites: [
      { type: 'node_completed', nodeId: 'C01' },
      { type: 'branch_selected', branchGroup: 'cell_identity_1' },
    ],
    conditions: [{ type: 'node_completed', nodeId: 'C06' }],
    rewards: [{ type: 'grant_adaptation_points', amount: 2 }],
    cta: { type: 'node', targetId: 'C03', label: 'Развить Protein Synthesis' },
    highlight: { type: 'node', targetId: 'C03' },
    hintTimeoutMs: 150000,
    hint: 'Protein Synthesis -> Organelles -> Cell Coordination готовят клетку к Multicellularity. Photosynthesis/Chemosynthesis/Efficient Digestion остаются опциональными.',
  },
  {
    id: 'G008', title: 'Освойте адаптации', description: 'Потратьте Adaptation Point на одну optional body adaptation.',
    targetTimeMs: 1320000, chapterId: 'CH03', slot: 'chapter', sequence: { previousGoalId: 'G007', nextGoalId: 'G009' },
    prerequisites: [{ type: 'node_completed', nodeId: 'C06' }], conditions: [{ type: 'adaptation_selected', count: 1 }], rewards: [],
    cta: { type: 'node', targetId: 'B02A', label: 'Выбрать адаптацию' }, highlight: { type: 'node', targetId: 'B02A' },
    hintTimeoutMs: 120000, hint: 'Adaptation Points не производятся со временем: они расходуются только на optional adaptations.',
  },
  {
    id: 'G009', title: 'Станьте многоклеточным', description: 'Завершите C07 Multicellularity.',
    targetTimeMs: 1560000, nodeId: 'C07', chapterId: 'CH03', slot: 'chapter', sequence: { previousGoalId: 'G008', nextGoalId: 'G010' },
    prerequisites: [{ type: 'node_completed', nodeId: 'C06' }, { type: 'adaptation_selected', count: 1 }], conditions: [{ type: 'node_completed', nodeId: 'C07' }], rewards: [],
    cta: { type: 'node', targetId: 'C07', label: 'Развить Multicellularity' }, highlight: { type: 'node', targetId: 'C07' },
    hintTimeoutMs: 180000, hint: 'Согласуйте клетки в единый организм, когда накопите Biomass, ATP и DNA.',
  },
  { id: 'G010', title: 'Специализируйте тело', description: 'Развейте B03 Tissue Specialization.', targetTimeMs: 1860000, nodeId: 'B03', chapterId: 'CH03', slot: 'chapter', sequence: { previousGoalId: 'G009', nextGoalId: 'G011' }, prerequisites: [{ type: 'node_completed', nodeId: 'C07' }], conditions: [{ type: 'node_completed', nodeId: 'B03' }], rewards: [], cta: { type: 'node', targetId: 'B03' }, highlight: { type: 'node', targetId: 'B03' } },
  { id: 'G011', title: 'Развейте органы чувств', description: 'Развейте B04 Nervous Tissue.', targetTimeMs: 1980000, nodeId: 'B04', chapterId: 'CH03', slot: 'chapter', sequence: { previousGoalId: 'G010', nextGoalId: 'G012' }, prerequisites: [{ type: 'node_completed', nodeId: 'B03' }], conditions: [{ type: 'node_completed', nodeId: 'B04' }], rewards: [], cta: { type: 'node', targetId: 'B04' }, highlight: { type: 'node', targetId: 'B04' } },
  { id: 'G012', title: 'Создайте нервную систему', description: 'Завершите B05 Nervous System.', targetTimeMs: 2100000, nodeId: 'B05', chapterId: 'CH03', slot: 'chapter', sequence: { previousGoalId: 'G011', nextGoalId: 'G013' }, prerequisites: [{ type: 'node_completed', nodeId: 'B04' }], conditions: [{ type: 'node_completed', nodeId: 'B05' }], rewards: [], cta: { type: 'node', targetId: 'B05' }, highlight: { type: 'node', targetId: 'B05' } },
  { id: 'G013', title: 'Пробудите разум', description: 'Доведите Cognition до 100 и завершите Sapience.', targetTimeMs: 2400000, nodeId: 'N07', chapterId: 'CH03', slot: 'chapter', sequence: { previousGoalId: 'G012' }, prerequisites: [{ type: 'node_completed', nodeId: 'B05' }], conditions: [{ type: 'node_completed', nodeId: 'N07' }], rewards: [], cta: { type: 'node', targetId: 'N03' }, highlight: { type: 'node', targetId: 'N03' } },
  { id: 'G014', title: 'Обеспечьте первую группу', description: 'Назначьте работы, накопите Food и постройте Hearth.', targetTimeMs: 2700000, chapterId: 'CH04', slot: 'chapter', sequence: { previousGoalId: 'G013', nextGoalId: 'G015' }, prerequisites: [{ type: 'era_reached', eraId: 'EARLY_CIV' }], conditions: [{ type: 'resource_amount', resourceId: 'food', amount: 100 }, { type: 'building_count', buildingId: 'BLD_HEARTH', count: 1 }], rewards: [], cta: { type: 'building', targetId: 'BLD_HEARTH' }, highlight: { type: 'building', targetId: 'BLD_HEARTH' } },
  { id: 'G015', title: 'Создайте племя', description: 'Постройте Shelter и доведите Population до 8.', targetTimeMs: 3000000, chapterId: 'CH04', slot: 'chapter', sequence: { previousGoalId: 'G014' }, prerequisites: [{ type: 'building_count', buildingId: 'BLD_HEARTH', count: 1 }], conditions: [{ type: 'building_count', buildingId: 'BLD_SHELTER', count: 1 }, { type: 'population_at_least', value: 8 }], rewards: [], cta: { type: 'building', targetId: 'BLD_SHELTER' }, highlight: { type: 'building', targetId: 'BLD_SHELTER' } },
  {
    id: 'G006_C04A_OPTIONAL',
    title: 'Optional: разовейте фотосинтез',
    description: 'C04A Photosynthesis даёт пассивный источник ATP, но не обязателен для основного пути.',
    targetTimeMs: 900000,
    nodeId: 'C04A',
    chapterId: 'CH02',
    slot: 'side',
    optional: true,
    prerequisites: [{ type: 'node_completed', nodeId: 'C01' }],
    conditions: [{ type: 'node_completed', nodeId: 'C04A' }],
    rewards: [],
    cta: { type: 'node', targetId: 'C04A', label: 'Развить Photosynthesis' },
    highlight: { type: 'node', targetId: 'C04A' },
    hintTimeoutMs: 150000,
    hint: 'Это optional-адаптация: усиливает ATP, но не блокирует Protein Synthesis.',
  },
  {
    id: 'G006_C04B_OPTIONAL',
    title: 'Optional: разовейте хемосинтез',
    description: 'C04B Chemosynthesis даёт источник ATP, не зависящий от внешней среды.',
    targetTimeMs: 900000,
    nodeId: 'C04B',
    chapterId: 'CH02',
    slot: 'side',
    optional: true,
    prerequisites: [{ type: 'node_completed', nodeId: 'C01' }],
    conditions: [{ type: 'node_completed', nodeId: 'C04B' }],
    rewards: [],
    cta: { type: 'node', targetId: 'C04B', label: 'Развить Chemosynthesis' },
    highlight: { type: 'node', targetId: 'C04B' },
    hintTimeoutMs: 150000,
    hint: 'Это optional-адаптация: усиливает ATP, но не блокирует Protein Synthesis.',
  },
  {
    id: 'G006_C04C_OPTIONAL',
    title: 'Optional: разовейте эффективное пищеварение',
    description: 'C04C Efficient Digestion повышает эффективность конверсии Biomass.',
    targetTimeMs: 900000,
    nodeId: 'C04C',
    chapterId: 'CH02',
    slot: 'side',
    optional: true,
    prerequisites: [{ type: 'node_completed', nodeId: 'C01' }],
    conditions: [{ type: 'node_completed', nodeId: 'C04C' }],
    rewards: [],
    cta: { type: 'node', targetId: 'C04C', label: 'Развить Efficient Digestion' },
    highlight: { type: 'node', targetId: 'C04C' },
    hintTimeoutMs: 150000,
    hint: 'Это optional-адаптация: усиливает Biomass, но не блокирует Protein Synthesis.',
  },
  {
    id: 'G016',
    targetTimeMs: 3720000,
    nodeId: 'T08',
    chapterId: 'CH04',
    prerequisites: [{ type: 'node_completed', nodeId: 'T07' }],
    conditions: [{ type: 'node_completed', nodeId: 'T08' }],
  },
];
