export const branchGroups = {
  cell_identity_1: ['C02A', 'C02B', 'C02C'],
  behavior_1: ['N02A', 'N02B', 'N02C'],
  culture_1: ['T01A', 'T01B', 'T01C'],
};

export const branchCostRules = {
  cell_identity_1: {
    allowAdditionalBranches: false,
  },
};

export const nodes = [
  {
    id: 'M01',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M01',
    cost: { rna: 9 },
    requiresNodes: [],
    effects: [
      { type: 'manual_gain_multiplier', value: 2 },
      { type: 'unlock_auto_production' },
    ],
    goalId: 'G001',
  },
  {
    id: 'M02',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M02',
    cost: { rna: 130 },
    requiresNodes: ['M01'],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'rna', value: 1.75 },
    ],
    goalId: 'G002',
  },
  {
    id: 'M03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M03',
    cost: { rna: 350 },
    requiresNodes: ['M02'],
    effects: [
      { type: 'unlock_resource', resourceId: 'dna' },
      { type: 'resource_production_multiplier', resourceId: 'rna', value: 1.15 },
    ],
    goalId: 'G003',
  },
  {
    id: 'M04',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.M04',
    cost: { rna: 450, dna: 120 },
    requiresNodes: ['M03'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'dna', value: 1.45 }],
  },
  {
    id: 'M05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M05',
    cost: { rna: 520, dna: 90 },
    requiresNodes: ['M03'],
    effects: [
      { type: 'global_production_multiplier', value: 1.12 },
    ],
    goalId: 'G004',
  },
  {
    id: 'M06',
    entityType: 'node',
    type: 'CONVERGENCE',
    semanticRole: 'breakthrough',
    labelKey: 'node.M06',
    cost: { rna: 930, dna: 205 },
    requiresNodes: ['M05'],
    effects: [{ type: 'unlock_resource', resourceId: 'biomass' }],
    transition: 'CELLULAR',
    goalId: 'G005',
  },
  {
    id: 'C01',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C01',
    cost: { biomass: 10 },
    requiresNodes: ['M06'],
    effects: [{ type: 'unlock_resource', resourceId: 'atp' }],
  },
  {
    id: 'C02A',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'cell_identity_1',
    labelKey: 'node.C02A',
    cost: { biomass: 30, atp: 15 },
    requiresNodes: ['C01'],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.18 },
      { type: 'set_flag', flag: 'run.bio.primary_trait', value: 'absorption' },
      { type: 'set_flag', flag: 'run.bio.absorption', value: true },
    ],
  },
  {
    id: 'C02B',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'cell_identity_1',
    labelKey: 'node.C02B',
    cost: { biomass: 30, atp: 15 },
    requiresNodes: ['C01'],
    effects: [
      { type: 'global_production_multiplier', value: 1.12 },
      { type: 'set_flag', flag: 'run.bio.primary_trait', value: 'symbiosis' },
      { type: 'set_flag', flag: 'run.bio.symbiosis', value: true },
    ],
  },
  {
    id: 'C02C',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'cell_identity_1',
    labelKey: 'node.C02C',
    cost: { biomass: 30, atp: 15 },
    requiresNodes: ['C01'],
    effects: [
      { type: 'producer_cost_multiplier', producerTag: 'biomass', value: 0.9 },
      { type: 'set_flag', flag: 'run.bio.primary_trait', value: 'shell' },
      { type: 'set_flag', flag: 'run.bio.shell', value: true },
    ],
  },
  {
    id: 'C03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C03',
    cost: { biomass: 110, atp: 50 },
    requiresAnyBranchGroup: 'cell_identity_1',
    effects: [{ type: 'resource_production_multiplier', resourceId: 'atp', value: 1.25 }],
  },
  {
    id: 'C04A',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.C04A',
    cost: { atp: 40 },
    requiresNodes: ['C01'],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'atp', value: 1.15 },
      { type: 'set_flag', flag: 'run.bio.metabolism.photosynthesis', value: true },
    ],
  },
  {
    id: 'C04B',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.C04B',
    cost: { biomass: 45 },
    requiresNodes: ['C01'],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'atp', value: 1.15 },
      { type: 'set_flag', flag: 'run.bio.metabolism.chemosynthesis', value: true },
    ],
  },
  {
    id: 'C04C',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.C04C',
    cost: { biomass: 35, dna: 15 },
    requiresNodes: ['C01'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.15 }],
  },
  {
    id: 'C05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C05',
    cost: { biomass: 160, atp: 70 },
    requiresNodes: ['C03'],
    effects: [{ type: 'global_production_multiplier', value: 1.15 }],
  },
  {
    id: 'C06',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C06',
    cost: { biomass: 170, atp: 100, dna: 160 },
    requiresNodes: ['C05'],
    effects: [{ type: 'global_production_multiplier', value: 1.1 }],
    goalId: 'G007',
  },
  {
    id: 'B02A', entityType: 'node', type: 'OPTIONAL', semanticRole: 'adaptation', labelKey: 'node.B02A',
    adaptationPointCost: 1, cost: { biomass: 55, atp: 30 }, requiresNodes: ['C06'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.12 }],
  },
  {
    id: 'B02B', entityType: 'node', type: 'OPTIONAL', semanticRole: 'adaptation', labelKey: 'node.B02B',
    adaptationPointCost: 1, cost: { biomass: 45, atp: 35 }, requiresNodes: ['C06'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'atp', value: 1.12 }],
  },
  {
    id: 'B02C', entityType: 'node', type: 'OPTIONAL', semanticRole: 'adaptation', labelKey: 'node.B02C',
    adaptationPointCost: 1, cost: { biomass: 65, atp: 25 }, requiresNodes: ['C06'],
    effects: [{ type: 'global_production_multiplier', value: 1.06 }],
  },
  {
    id: 'B02D', entityType: 'node', type: 'OPTIONAL', semanticRole: 'adaptation', labelKey: 'node.B02D',
    adaptationPointCost: 2, cost: { biomass: 85, atp: 40, dna: 30 }, requiresNodes: ['C06'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.1 }],
  },
  {
    id: 'C07', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.C07',
    cost: { biomass: 250, atp: 140, dna: 210 }, requiresNodes: ['C06'], effects: [], transition: 'MULTICELLULAR', goalId: 'G009',
  },
  { id: 'B03', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.B03', cost: { biomass: 320, atp: 180, dna: 260 }, requiresNodes: ['C07'], effects: [] },
  { id: 'B04', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.B04', cost: { biomass: 390, atp: 220, dna: 310 }, requiresNodes: ['B03'], effects: [], cognitionContribution: 20 },
  { id: 'B05', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.B05', cost: { biomass: 460, atp: 270, dna: 380 }, requiresNodes: ['B04'], effects: [], cognitionContribution: 25 },
  { id: 'N02A', entityType: 'node', type: 'BRANCH', semanticRole: 'branch', branchGroup: 'behavior_1', labelKey: 'node.N02A', cost: { biomass: 90, atp: 45 }, requiresNodes: ['B05'], effects: [{ type: 'set_flag', flag: 'run.bio.behavior', value: 'solitary' }] },
  { id: 'N02B', entityType: 'node', type: 'BRANCH', semanticRole: 'branch', branchGroup: 'behavior_1', labelKey: 'node.N02B', cost: { biomass: 90, atp: 45 }, requiresNodes: ['B05'], effects: [{ type: 'set_flag', flag: 'run.bio.behavior', value: 'social' }] },
  { id: 'N02C', entityType: 'node', type: 'BRANCH', semanticRole: 'branch', branchGroup: 'behavior_1', labelKey: 'node.N02C', cost: { biomass: 90, atp: 45 }, requiresNodes: ['B05'], effects: [{ type: 'set_flag', flag: 'run.bio.behavior', value: 'tool_use' }] },
  { id: 'N03', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.N03', cost: { biomass: 500, atp: 300, dna: 440 }, requiresNodes: ['B05'], requiresAnyBranchGroup: 'behavior_1', effects: [], cognitionContribution: 30 },
  { id: 'N05', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.N05', cost: { biomass: 560, atp: 340, dna: 500 }, requiresNodes: ['N03'], effects: [], cognitionContribution: 25 },
  { id: 'N07', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.N07', cost: {}, requiresNodes: ['N05'], cognitionMin: 100, cognitionContributions: [{ nodeId: 'B04', value: 20 }, { nodeId: 'B05', value: 25 }, { nodeId: 'N03', value: 30 }, { nodeId: 'N05', value: 25 }], effects: [], transition: 'EARLY_CIV', goalId: 'G013' },
  {
    id: 'T01A',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01A',
    cost: { food: 250, materials: 120, knowledge: 35 },
    requiresNodes: [],
    effects: [
      { type: 'job_output_multiplier', jobId: 'JOB_TRIBE_FORAGER', value: 1.35 },
    ],
  },
  {
    id: 'T01B',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01B',
    cost: { food: 220, materials: 100, knowledge: 40 },
    requiresNodes: [],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'food', value: 1.15 },
      { type: 'resource_production_multiplier', resourceId: 'materials', value: 1.15 },
    ],
  },
  {
    id: 'T01C',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01C',
    cost: { food: 230, materials: 110, knowledge: 45 },
    requiresNodes: [],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'knowledge', value: 1.25 },
    ],
  },
  {
    id: 'T02',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T02',
    cost: { food: 420, materials: 240, knowledge: 60 },
    requiresAnyBranchGroup: 'culture_1',
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'food', value: 1.2 },
    ],
    goalId: 'G014',
  },
  {
    id: 'T03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T03',
    cost: { food: 610, materials: 330, knowledge: 95 },
    requiresNodes: ['T02'],
    effects: [
      { type: 'job_output_multiplier', jobId: 'JOB_TRIBE_FORAGER', value: 1.25 },
    ],
    goalId: 'G014',
  },
  {
    id: 'T05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'breakthrough',
    labelKey: 'node.T05',
    cost: { food: 900, materials: 520, knowledge: 145 },
    requiresNodes: ['T03'],
    populationMin: 8,
    effects: [],
    transition: 'TRIBE',
    goalId: 'G015',
  },
  {
    id: 'T07',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T07',
    cost: { food: 1150, materials: 620, knowledge: 210 },
    requiresNodes: ['T05'],
    effects: [],
  },
  {
    id: 'T08',
    entityType: 'node',
    type: 'CONVERGENCE',
    semanticRole: 'breakthrough',
    labelKey: 'node.T08',
    cost: { food: 1650, materials: 900, knowledge: 300 },
    requiresNodes: ['T07'],
    populationMin: 14,
    effects: [{ type: 'unlock_building', buildingId: 'BLD_FIELD' }],
    transition: 'SETTLEMENT_EARLY',
    goalId: 'G016',
  },
  {
    id: 'T09', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.T09',
    cost: { food: 2100, materials: 1150, knowledge: 390 }, requiresNodes: ['T08'], populationMin: 14,
    requiresBuildings: [{ buildingId: 'BLD_FIELD', count: 1 }, { buildingId: 'BLD_HOUSE', count: 1 }, { buildingId: 'BLD_WORKSHOP', count: 1 }],
    effects: [{ type: 'unlock_building', buildingId: 'BLD_SCHOOL' }], transition: 'SETTLEMENT', goalId: 'G017',
  },
  {
    id: 'T10', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.T10',
    cost: { food: 2700, materials: 1450, knowledge: 520 }, requiresNodes: ['T09'],
    effects: [{ type: 'unlock_building', buildingId: 'BLD_MARKET' }], goalId: 'G018',
  },
  {
    id: 'T11', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.T11',
    cost: { food: 3300, materials: 1800, knowledge: 690 }, requiresNodes: ['T10'], effects: [],
  },
  {
    id: 'T12', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.T12',
    cost: { food: 4100, materials: 2300, knowledge: 880 }, requiresNodes: ['T11'], populationMin: 28,
    requiresBuildings: [{ buildingId: 'BLD_SCHOOL', count: 1 }, { buildingId: 'BLD_MARKET', count: 1 }], effects: [], transition: 'CITY', goalId: 'G019',
  },
  {
    id: 'T13', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.T13',
    cost: { food: 4600, materials: 2900, knowledge: 1120 }, requiresNodes: ['T12'],
    effects: [{ type: 'unlock_building', buildingId: 'BLD_FACTORY' }], goalId: 'G020',
  },
  {
    id: 'T14', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.T14',
    cost: { food: 5100, materials: 3500, knowledge: 1380 }, requiresNodes: ['T13'],
    effects: [{ type: 'unlock_building', buildingId: 'BLD_RAIL_HUB' }],
  },
  {
    id: 'T15', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.T15',
    cost: { materials: 4400, knowledge: 1720 }, requiresNodes: ['T14'], populationMin: 46,
    requiresBuildings: [{ buildingId: 'BLD_FACTORY', count: 1 }, { buildingId: 'BLD_STEAM_PLANT', count: 1 }],
    effects: [{ type: 'unlock_building', buildingId: 'BLD_GRID' }], transition: 'INDUSTRY', goalId: 'G021',
  },
  {
    id: 'T16', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.T16',
    cost: { materials: 7290, knowledge: 2970, power: 702 }, requiresNodes: ['T15'],
    requiresBuildings: [{ buildingId: 'BLD_GRID', count: 1 }], effects: [],
  },
  {
    id: 'T17', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.T17',
    cost: { materials: 7965, knowledge: 3780, power: 918 }, requiresNodes: ['T16'],
    requiresBuildings: [{ buildingId: 'BLD_LABORATORY', count: 1 }], effects: [],
  },
  {
    id: 'T18', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.T18',
    cost: { materials: 8775, knowledge: 4590, power: 1161 }, requiresNodes: ['T17'], populationMin: 62,
    requiresBuildings: [{ buildingId: 'BLD_RAIL_HUB', count: 1 }], effects: [], transition: 'MODERN', goalId: 'G022',
  },
  {
    id: 'A01', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.A01',
    cost: { materials: 9585, knowledge: 5535, power: 1485 }, requiresNodes: ['T18'], effects: [], transition: 'PRE_ATOMIC',
  },
  {
    id: 'A02', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.A02',
    cost: { materials: 10530, knowledge: 6615, power: 1823 }, requiresNodes: ['A01'],
    effects: [{ type: 'unlock_building', buildingId: 'BLD_REACTOR_LAB' }],
  },
  {
    id: 'A03', entityType: 'node', type: 'CORE', semanticRole: 'core_tech', labelKey: 'node.A03',
    cost: { materials: 11610, knowledge: 7830, power: 2160 }, requiresNodes: ['A02'],
    requiresBuildings: [{ buildingId: 'BLD_REACTOR_LAB', count: 1 }], effects: [],
  },
  {
    id: 'A04', entityType: 'node', type: 'CONVERGENCE', semanticRole: 'breakthrough', labelKey: 'node.A04',
    cost: { materials: 12420, knowledge: 8640, power: 2430 }, requiresNodes: ['A03'], populationMin: 74,
    effects: [], transition: 'ATOMIC', goalId: 'G023',
  },
];
