export const branchGroups = {
  metabolism_1: ['C01A', 'C01B', 'C01C'],
  culture_1: ['T01A', 'T01B', 'T01C'],
};

export const branchCostRules = {
  metabolism_1: {
    allowAdditionalBranches: true,
    additionalBranchCostMultiplier: 2.5,
    waiveWithArchiveNodeId: 'AR06',
  },
};

export const nodes = [
  {
    id: 'M01',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M01',
    cost: { energy: 12 },
    requiresNodes: [],
    effects: [
      { type: 'manual_gain_multiplier', value: 2 },
      { type: 'unlock_auto_production' },
    ],
    goalId: 'G001',
  },
  {
    id: 'M02',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M02',
    cost: { energy: 40, information: 3 },
    requiresNodes: ['M01'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'information', value: 1.6 }],
    goalId: 'G002',
  },
  {
    id: 'M03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M03',
    cost: { energy: 90, information: 10 },
    requiresNodes: ['M02'],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'energy', value: 1.35 },
      { type: 'resource_production_multiplier', resourceId: 'information', value: 1.25 },
    ],
    goalId: 'G003',
  },
  {
    id: 'M04',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.M04',
    cost: { energy: 145, information: 18 },
    requiresNodes: ['M03'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'information', value: 1.4 }],
  },
  {
    id: 'M05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M05',
    cost: { energy: 210, information: 28 },
    requiresNodes: ['M03'],
    effects: [{ type: 'global_production_multiplier', value: 1.2 }],
    goalId: 'G004',
  },
  {
    id: 'M06',
    entityType: 'node',
    type: 'CONVERGENCE',
    semanticRole: 'breakthrough',
    labelKey: 'node.M06',
    cost: { energy: 520, information: 80 },
    requiresNodes: ['M05'],
    effects: [{ type: 'unlock_resource', resourceId: 'biomass' }],
    transition: 'CELLULAR',
    goalId: 'G005',
  },
  {
    id: 'C01B',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'metabolism_1',
    labelKey: 'node.C01B',
    cost: { energy: 150, information: 45 },
    requiresNodes: ['M06'],
    effects: [{ type: 'producer_cost_multiplier', producerTag: 'energy', value: 0.88 }],
  },
  {
    id: 'C01A',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'metabolism_1',
    labelKey: 'node.C01A',
    cost: { energy: 180, information: 55 },
    requiresNodes: ['M06'],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'energy', value: 1.45 },
      { type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.1 },
    ],
  },
  {
    id: 'C01C',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'metabolism_1',
    labelKey: 'node.C01C',
    cost: { energy: 120, information: 40 },
    requiresNodes: ['M06'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.35 }],
  },
  {
    id: 'T01A',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01A',
    cost: { food: 250, materials: 120, knowledge: 35 },
    requiresNodes: [],
    effects: [
      { type: 'job_output_multiplier', jobId: 'JOB_TRIBE_FORAGER', value: 1.35, deferred: true, deferredUntil: 'jobs_system' },
    ],
  },
  {
    id: 'T01B',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01B',
    cost: { food: 220, materials: 100, knowledge: 40 },
    requiresNodes: [],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'food', value: 1.15 },
      { type: 'resource_production_multiplier', resourceId: 'materials', value: 1.15 },
    ],
  },
  {
    id: 'T01C',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01C',
    cost: { food: 230, materials: 110, knowledge: 45 },
    requiresNodes: [],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'knowledge', value: 1.25 }],
  },
  {
    id: 'T02',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T02',
    cost: { food: 420, materials: 240, knowledge: 60 },
    requiresAnyBranchGroup: 'culture_1',
    effects: [{ type: 'resource_production_multiplier', resourceId: 'food', value: 1.2 }],
    goalId: 'G014',
  },
  {
    id: 'T03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T03',
    cost: { food: 610, materials: 330, knowledge: 95 },
    requiresNodes: ['T02'],
    effects: [
      { type: 'job_output_multiplier', jobId: 'JOB_TRIBE_FORAGER', value: 1.25, deferred: true, deferredUntil: 'jobs_system' },
    ],
    goalId: 'G014',
  },
  {
    id: 'T05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'breakthrough',
    labelKey: 'node.T05',
    cost: { food: 900, materials: 520, knowledge: 145 },
    requiresNodes: ['T03'],
    populationMin: 32,
    effects: [],
    transition: 'TRIBE',
    goalId: 'G015',
  },
  {
    id: 'T07',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T07',
    cost: { food: 1150, materials: 620, knowledge: 210 },
    requiresNodes: ['T05'],
    effects: [],
  },
  {
    id: 'T08',
    entityType: 'node',
    type: 'CONVERGENCE',
    semanticRole: 'breakthrough',
    labelKey: 'node.T08',
    cost: { food: 1650, materials: 900, knowledge: 300 },
    requiresNodes: ['T07'],
    populationMin: 42,
    effects: [{ type: 'unlock_building', buildingId: 'BLD_FIELD' }],
    transition: 'SETTLEMENT_EARLY',
    goalId: 'G016',
  },
];
