export const branchGroups = {
  cell_identity_1: ['C02A', 'C02B', 'C02C'],
  culture_1: ['T01A', 'T01B', 'T01C'],
};

export const branchCostRules = {
  cell_identity_1: {
    allowAdditionalBranches: false,
  },
};

export const nodes = [
  {
    id: 'M01',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M01',
    cost: { rna: 9 },
    requiresNodes: [],
    effects: [
      { type: 'manual_gain_multiplier', value: 2 },
      { type: 'unlock_auto_production' },
    ],
    goalId: 'G001',
  },
  {
    id: 'M02',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M02',
    cost: { rna: 130 },
    requiresNodes: ['M01'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'rna', value: 1.75 }],
    goalId: 'G002',
  },
  {
    id: 'M03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M03',
    cost: { rna: 350 },
    requiresNodes: ['M02'],
    effects: [
      { type: 'unlock_resource', resourceId: 'dna' },
      { type: 'resource_production_multiplier', resourceId: 'rna', value: 1.15 },
    ],
    goalId: 'G003',
  },
  {
    id: 'M04',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.M04',
    cost: { rna: 450, dna: 120 },
    requiresNodes: ['M03'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'dna', value: 1.45 }],
  },
  {
    id: 'M05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.M05',
    cost: { rna: 520, dna: 90 },
    requiresNodes: ['M03'],
    effects: [{ type: 'global_production_multiplier', value: 1.12 }],
    goalId: 'G004',
  },
  {
    id: 'M06',
    entityType: 'node',
    type: 'CONVERGENCE',
    semanticRole: 'breakthrough',
    labelKey: 'node.M06',
    cost: { rna: 930, dna: 205 },
    requiresNodes: ['M05'],
    effects: [{ type: 'unlock_resource', resourceId: 'biomass' }],
    transition: 'CELLULAR',
    goalId: 'G005',
  },
  {
    id: 'C01',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C01',
    cost: { biomass: 10 },
    requiresNodes: ['M06'],
    effects: [{ type: 'unlock_resource', resourceId: 'energy' }],
  },
  {
    id: 'C02A',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'cell_identity_1',
    labelKey: 'node.C02A',
    cost: { biomass: 30 },
    requiresNodes: ['C01'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.18 }],
  },
  {
    id: 'C02B',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'cell_identity_1',
    labelKey: 'node.C02B',
    cost: { biomass: 30, energy: 8 },
    requiresNodes: ['C01'],
    effects: [{ type: 'global_production_multiplier', value: 1.12 }],
  },
  {
    id: 'C02C',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'cell_identity_1',
    labelKey: 'node.C02C',
    cost: { biomass: 28, dna: 16 },
    requiresNodes: ['C01'],
    effects: [{ type: 'producer_cost_multiplier', producerTag: 'biomass', value: 0.9 }],
  },
  {
    id: 'C03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C03',
    cost: { biomass: 55, energy: 20 },
    requiresAnyBranchGroup: 'cell_identity_1',
    effects: [{ type: 'resource_production_multiplier', resourceId: 'energy', value: 1.25 }],
    goalId: 'G007',
  },
  {
    id: 'C04A',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.C04A',
    cost: { energy: 40 },
    requiresNodes: ['C01'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'energy', value: 1.15 }],
  },
  {
    id: 'C04B',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.C04B',
    cost: { biomass: 45 },
    requiresNodes: ['C01'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'energy', value: 1.15 }],
  },
  {
    id: 'C04C',
    entityType: 'node',
    type: 'OPTIONAL',
    semanticRole: 'upgrade',
    labelKey: 'node.C04C',
    cost: { biomass: 35, dna: 15 },
    requiresNodes: ['C01'],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'biomass', value: 1.15 }],
  },
  {
    id: 'C05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C05',
    cost: { biomass: 90, energy: 35 },
    requiresNodes: ['C03'],
    effects: [{ type: 'global_production_multiplier', value: 1.15 }],
    goalId: 'G008',
  },
  {
    id: 'C06',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.C06',
    cost: { biomass: 140, energy: 60, dna: 80 },
    requiresNodes: ['C05'],
    effects: [{ type: 'global_production_multiplier', value: 1.1 }],
    goalId: 'G009',
  },
  {
    id: 'T01A',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01A',
    cost: { food: 250, materials: 120, knowledge: 35 },
    requiresNodes: [],
    effects: [
      { type: 'job_output_multiplier', jobId: 'JOB_TRIBE_FORAGER', value: 1.35, deferred: true, deferredUntil: 'jobs_system' },
    ],
  },
  {
    id: 'T01B',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01B',
    cost: { food: 220, materials: 100, knowledge: 40 },
    requiresNodes: [],
    effects: [
      { type: 'resource_production_multiplier', resourceId: 'food', value: 1.15 },
      { type: 'resource_production_multiplier', resourceId: 'materials', value: 1.15 },
    ],
  },
  {
    id: 'T01C',
    entityType: 'node',
    type: 'BRANCH',
    semanticRole: 'branch',
    branchGroup: 'culture_1',
    labelKey: 'node.T01C',
    cost: { food: 230, materials: 110, knowledge: 45 },
    requiresNodes: [],
    effects: [{ type: 'resource_production_multiplier', resourceId: 'knowledge', value: 1.25 }],
  },
  {
    id: 'T02',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T02',
    cost: { food: 420, materials: 240, knowledge: 60 },
    requiresAnyBranchGroup: 'culture_1',
    effects: [{ type: 'resource_production_multiplier', resourceId: 'food', value: 1.2 }],
    goalId: 'G014',
  },
  {
    id: 'T03',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T03',
    cost: { food: 610, materials: 330, knowledge: 95 },
    requiresNodes: ['T02'],
    effects: [
      { type: 'job_output_multiplier', jobId: 'JOB_TRIBE_FORAGER', value: 1.25, deferred: true, deferredUntil: 'jobs_system' },
    ],
    goalId: 'G014',
  },
  {
    id: 'T05',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'breakthrough',
    labelKey: 'node.T05',
    cost: { food: 900, materials: 520, knowledge: 145 },
    requiresNodes: ['T03'],
    populationMin: 32,
    effects: [],
    transition: 'TRIBE',
    goalId: 'G015',
  },
  {
    id: 'T07',
    entityType: 'node',
    type: 'CORE',
    semanticRole: 'core_tech',
    labelKey: 'node.T07',
    cost: { food: 1150, materials: 620, knowledge: 210 },
    requiresNodes: ['T05'],
    effects: [],
  },
  {
    id: 'T08',
    entityType: 'node',
    type: 'CONVERGENCE',
    semanticRole: 'breakthrough',
    labelKey: 'node.T08',
    cost: { food: 1650, materials: 900, knowledge: 300 },
    requiresNodes: ['T07'],
    populationMin: 42,
    effects: [{ type: 'unlock_building', buildingId: 'BLD_FIELD' }],
    transition: 'SETTLEMENT_EARLY',
    goalId: 'G016',
  },
];
