export const producers = [
  {
    id: 'PROC_PRIMORDIAL_REACTION',
    entityType: 'producer',
    labelKey: 'producer.primordial_reaction',
    unlocksAtStart: true,
    tags: ['rna', 'process'],
    baseCost: { rna: 5 },
    growth: 1.14,
    output: { rna: 0.22 },
    producesBeforeAutoUnlock: true,
    enableMilestoneMultipliers: true,
    milestoneNarrative: 'At 10, isolated reactions link into a cooperative RNA reaction network.',
  },
  {
    id: 'PROC_RNA_REPLICATION',
    entityType: 'producer',
    labelKey: 'producer.rna_replication',
    requiresNodes: ['M02'],
    tags: ['rna', 'process', 'replication'],
    baseCost: { rna: 34 },
    growth: 1.16,
    output: { rna: 0.58 },
    enableMilestoneMultipliers: true,
    milestoneNarrative: 'At 10, copies start reinforcing the replication loop as a shared template pool.',
  },
  {
    id: 'PROC_DNA_SYNTHESIS',
    entityType: 'producer',
    labelKey: 'producer.dna_synthesis',
    requiresNodes: ['M03'],
    tags: ['dna', 'process'],
    baseCost: { rna: 78 },
    growth: 1.15,
    output: { dna: 0.24 },
    enableMilestoneMultipliers: true,
    milestoneNarrative: 'At 10, synthesis stabilizes into a reusable genetic assembly chain.',
  },
];
