export const producers = [
  {
    id: 'GEN_CHEMICAL_GRADIENT',
    entityType: 'producer',
    labelKey: 'producer.chemical_gradient',
    unlocksAtStart: true,
    tags: ['energy'],
    baseCost: { energy: 10 },
    growth: 1.15,
    output: { energy: 0.4 },
  },
  {
    id: 'GEN_CATALYTIC_FOLD',
    entityType: 'producer',
    labelKey: 'producer.catalytic_fold',
    requiresNodes: ['M01'],
    tags: ['information'],
    baseCost: { energy: 24 },
    growth: 1.17,
    output: { information: 0.055 },
  },
  {
    id: 'GEN_ENERGY_POCKET',
    entityType: 'producer',
    labelKey: 'producer.energy_pocket',
    requiresNodes: ['M02'],
    tags: ['energy'],
    baseCost: { energy: 38 },
    growth: 1.15,
    output: { energy: 0.75 },
  },
];
